export const contributorsList = [
    'Chandra Bossard',
    'Mollie Burke',
    'Jason Cooper',
    'Jack & Judy Davidson',
    'William Ericson',
    'Sabra Ewing',
    'Johnny Gifford',
    'Betsy Hall',
    'Erik Hammarlund',
    'John Hooper',
    'Nate King',
    'Prudence MacKinney',
    'Charles F. Monette',
    'Frederick Moriarty',
    'Brett Morrison',
    'Robert Oeser',
    'Paula Sagerman',
    'Walter Slowinski',
    'Leland Smith',
    'Hillary Twining',
    'Lissa Weinmann',
];
